### ISSUE TITLE
Failed to activate the linter-glsl package

### ISSUE THREAD

**Issue by Sasun** [AtomLinter/linter-glsl#26] opened 2016-04-17 16:32 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter-glsl](https://github.com/AtomLinter/linter-glsl) package, v2.0.1
### Stack Trace

Failed to activate the linter-glsl package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at module.exports (C:\Users\Sasun Poghosyan\.atom\packages\linter-glsl\node_modules\node-whereis\lib\whereis.js:6:39)
    at C:/Users/Sasun Poghosyan/.atom/packages/linter-glsl/lib/linter-glsl.js:225:20
    at Config.module.exports.Config.observeKeyPath (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\config.js:612:7)
    at Config.module.exports.Config.observe (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\config.js:141:21)
    at Object.activate (C:/Users/Sasun Poghosyan/.atom/packages/linter-glsl/lib/linter-glsl.js:216:19)
    at Package.module.exports.Package.activateNow (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:183:20)
    at C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:92:15)
    at C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Sasun Poghosyan\AppData\Local\atom\app-1.7.1\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -5:22.1.0 settings-view:open (atom-pane.pane.active)
     -5:20.5.0 key-binding-resolver:toggle (div.panels-item)
     -3:50.1.0 core:delete (atom-text-editor.editor.mini.is-focused)
  5x -3:21.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:55.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
autocomplete-glsl, v0.2.3
language-glsl, v2.0.1
linter, v1.11.4
linter-glsl, v2.0.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-04-20 17:42
Looks like this is a bug in `node-whereis`, I'll file an issue over there and see if the author is still maintaining it.

**Comment by Xyten** [comment] 2016-05-21 15:57
Is there no temporary workaround for this ?

**Comment by andystanton** [comment] 2016-05-21 19:24
Hi @Xyten and @Sasun,

I've switched out the `whereis` library with another that seems better maintained. Version 2.0.3 of linter-glsl has been released with this change - can you see if this helps with your issue?

**Comment by Xyten** [comment] 2016-05-22 17:58
@andystanton Hi! I can confirm that my glsl linter now works!

Thank you!

**Closed** 2017-02-11 23:18 UTC

**Comment by KC-SI** [comment] 2017-03-10 00:17
Getting this error in Atom 1.16.beta0.

**Comment by Arcanemagus** [comment] 2017-03-10 03:20
@KC-SI Are you getting this _exact_ error? If so you need to update `linter-glsl`.

It's more likely that you simply hit an APM bug that has been cropping up more recently where it fails to install all the required dependencies. You can try re-installing the package to attempt to fix that.

**Comment by KC-SI** [comment] 2017-03-11 23:27
Yes. Tried building it from git but still occuring. 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: "Arch Linux"
**Thrown From**: [linter-glsl](https://github.com/AtomLinter/linter-glsl) package 2.1.1


### Stack Trace

Failed to activate the linter-glsl package

```
At Cannot set property 'subscriptions' of undefined

TypeError: Cannot set property 'subscriptions' of undefined
    at Object.activate (linter-glsl.js:199:5)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
     -0:22.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.tinted-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-ariake-dark-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-clock 0.1.6 
atom-material-ui 1.3.9 
atom-ternjs 0.18.2 
atom-typescript 10.1.15 
autocomplete-glsl 0.2.3 
browser-plus 0.0.87 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.1 
file-icons 2.0.17 
filesize 2.0.4 
git-plus 7.3.3 
Hydrogen 1.6.0 
intentions 1.1.2 
intentions-colorpicker 1.0.1 
keyboard-sounds 0.2.0 
language-babel 2.56.2 
language-glsl 2.0.1 
language-lua 0.9.11 
language-moonscript 1.7.1 
language-pug 0.0.21 
linter 1.99.0 
linter-flow 5.5.0 
linter-glsl 2.1.1 
linter-js-standard 3.9.0 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-moonscript 1.1.1 
linter-ui-default 0.0.4 
linter-xmllint 1.4.1 
minimap 4.26.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
pigments 0.39.0 
processing 0.13.0 
processing-language 0.2.0 
sync-settings 0.8.1 
termination 0.5.0 
toggle-packages 1.1.0 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
```

**Comment by Arcanemagus** [comment] 2017-03-13 20:02
@KC-SI:  `TypeError: Cannot read property 'split' of undefined` is not the same thing as `TypeError: Cannot set property 'subscriptions' of undefined` 😛

Can you please file a new issue so we aren't spamming everyone in this thread trying to figure out what is going on?
